/*******************************************************************************
 * Copyright 2007(c) Genome Quebec. All rights reserved.
 * <p>
 * This file is part of GenoByte.
 * <p>
 * GenoByte is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 * <p>
 * GenoByte is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * <p>
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************/
package org.obiba.bitwise.query;

import org.obiba.bitwise.BitVector;
import org.obiba.bitwise.BitwiseStore;
import org.obiba.bitwise.Field;

/**
 * Finds all records included between two given bounds.
 */
public class RangeQuery extends Query {

  private String field_ = null;

  private String from_ = null;

  private String to_ = null;

  public RangeQuery(String field, String from, String to) {
    super();
    field_ = field;
    from_ = from;
    to_ = to;
  }

  @Override
  public QueryResult execute(BitwiseStore store) throws QueryExecutionException {
    Field f = store.getField(field_);
    if (f == null) {
      throw invalidField(store, field_);
    }

    //It only makes sense to run a range query  on values generated by an ordered dictionary.
    if (!(f.getDictionary().isOrdered())) {
      throw new InvalidQueryTypeException(store.getName(), f.getName(),
          "Range queries can only be ran on orderable fields.");
    }

    Object from = f.getDictionary().convert(from_);
    if (from == null) {
      throw invalidFieldValue(store, field_, from_);
    }
    Object to = f.getDictionary().convert(to_);
    if (to == null) {
      throw invalidFieldValue(store, field_, to_);
    }
    BitVector vFrom = f.getDictionary().lookup(from);
    if (vFrom == null) {
      vFrom = new BitVector(f.getDictionary().dimension());
    }
    BitVector vTo = f.getDictionary().lookup(to);
    if (vTo == null) {
      vTo = new BitVector(f.getDictionary().dimension());
    }
    return f.rangeQuery(vFrom, vTo);
  }

  /**
   * Creates a <tt>String</tt> representation of this query.
   */
  @Override
  public String toString() {
    StringBuffer sb = new StringBuffer();
    sb.append(field_).append("=[").append(from_).append(" TO ").append(to_).append("]");
    return sb.toString();
  }
}
